- name: add motd file
  template:
    src: "{{_motd_template.key}}.j2"
    dest: "{{motd_d_path}}/{{_motd_template.value.filename|default(_motd_template.key)}}"
    owner: root
    mode: 0644
  with_dict: "{{_motd_dict}}"
  loop_control:
    loop_var: _motd_template
  when: >
    _motd_template.value.state is undefined or
    _motd_template.value.state != "absent"

- name: remove motd file
  file:
    path: "{{motd_d_path}}/{{_motd_template.value.filename|default(_motd_template.key)}}"
    state: absent
  with_dict: "{{_motd_dict}}"
  loop_control:
    loop_var: _motd_template
  when: >
    _motd_template.value.state is defined and
    _motd_template.value.state == "absent"
