- name: set windows hardware clock to UTC
  ansible.builtin.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\TimeZoneInformation
    name: RealTimeIsUniversal
    data: 1
    type: dword

# this needs a new login for SSH sessions, but seems to directly change
# for the desktop and running WSL instances. Given that usually we only set
# that at the very beginning, before anything else is up, it's probably fine
# not to force a reboot.
- name: set windows timezone
  ansible.builtin.win_timezone:
    timezone: "{{host_timezone_win}}"

- name: start windows time service, if necessary
  ansible.builtin.win_service:
    name: w32time
    start_mode: auto
    state: started
  when: >
    ntp_servers is defined and
    (windows_time is undefined or windows_time == "ntp")

- name: configure NTP servers
  ansible.builtin.win_command: w32tm /config /manualpeerlist:"{{ ntp_servers|join(' ') }}" /reliable:yes /update
  changed_when: false
  when: >
    ntp_servers is defined and
    (windows_time is undefined or windows_time == "ntp")