- ansible.builtin.include_tasks: _firewalld_mandatory_setup.yml
  when: >
    firewalld_required is defined and firewalld_required == True

- name: check if firewalld is available and working
  firewalld:
    zone: block
    state: enabled
    permanent: no
  register: firewalld_result
  ignore_errors: True

- name: register firewalld status
  set_fact:
    firewalld_available: True
  when: firewalld_result is succeeded

- name: setup firewalld
  include: _firewalld_setup.yml
  when: >
    firewalld_available == False and
    firewalld_required is defined and firewalld_required == True

- ansible.builtin.include_tasks: _firewalld.yml
  when: >
    firewalld_available == True