- name: set defaults for transactional variables
  ansible.builtin.set_fact:
    transactional_system: false
  tags:
    - base_config
    - access_setup

- name: check for transactional-update
  stat:
    path: "/sbin/transactional-update"
  register: marker
  when: >
    ansible_system == 'Linux'
  tags:
    - base_config
    - access_setup

- name: drop root .ssh (provisioning)
  ansible.builtin.set_fact:
    transactional_system: true
  when:  >
    ansible_system == 'Linux' and
    marker.stat.exists == True
  tags:
    - base_config
    - access_setup
