- name: verify ansible version
  ansible.builtin.assert:
    that: "ansible_version.full is version_compare('2.14.0', '>=')"
    msg: >
      Minimum ansible version required for running this is 2.14
  tags:
    - base_config
    - access_setup

- name: verify site ansible version
  ansible.builtin.assert:
    that: "ansible_version.full is version_compare('{{site_ansible_version}}', '=')"
    msg: >
      This site expects ansible version {{site_ansible_version}}, while you are using
      {{ansible_version.full}}.

      Install the correct version with pip3 install ansible=={{site_ansible_version}}

      When using default locations aliases can be set as follows, adjusting X and Y
      for the correct versions:

        alias ansibleXY=~/.local/bin/ansible
        alias ansibleXY-playbook=~/.local/bin/ansible-playbook
  when: site_ansible_version is defined
  tags:
    - base_config
    - access_setup

- ansible.builtin.set_fact:
    data_utilities_version: 0.10
  tags:
    - base_config
    - access_setup

- ansible.builtin.assert:
    that: "data_utilities_version is version_compare(data_utilities_minver, '>=')"
    msg: >
      Minimum data-utilities version required for running this is {{data_utilities_minver}}.
      This is version {{data_utilities_version}}. Grab a new release from:
      https://github.com/aardsoft/ansible-data-utilities
  when: data_utilities_minver is defined
  tags:
    - base_config
    - access_setup

- ansible.builtin.include_tasks: default_variables.yml
  tags:
    - base_config
    - access_setup
