- ansible.builtin.set_fact:
    is_wsl: False
  tags:
    - base_config
    - access_setup

- ansible.builtin.set_fact: firewalld_available=False
  when: firewalld_available is undefined
  tags:
    - base_config
    - access_setup

# admin user setup
- ansible.builtin.set_fact:
    adm_uid: 10000
  when: adm_uid is undefined
  tags:
    - base_config
    - access_setup

- ansible.builtin.set_fact:
    adm_gid: 10000
  when: adm_gid is undefined
  tags:
    - base_config
    - access_setup

- ansible.builtin.set_fact:
    adm_user: management
  when: adm_user is undefined
  tags:
    - base_config
    - access_setup

- ansible.builtin.set_fact:
    adm_group: management
  when: adm_group is undefined
  tags:
    - base_config
    - access_setup

- ansible.builtin.set_fact:
    _root_group: "{% if ansible_os_family == 'Darwin' %}wheel{% else %}root{% endif %}"
    _root_user: root
  tags:
    - base_config
    - access_setup

- name: dump_config override root
  ansible.builtin.set_fact:
    _root_group: "{{lookup('env', 'USER')}}"
    _root_user: "{{lookup('env', 'USER')}}"
  when: dump_config is defined
  tags:
    - base_config
    - access_setup

- ansible.builtin.set_fact:
    _delegation: "{%if dump_config is defined %}localhost{% else %}{{inventory_host}}{% endif %}"
  tags:
    - base_config
    - access_setup
