- ansible.builtin.set_fact: role_name="undefined"
  when: role_name is undefined

- ansible.builtin.set_fact:
    _packages: "{{role_packages}}"
  when: role_packages is defined

- ansible.builtin.set_fact:
    _packages: "{{packages}}"
  when: packages is defined and role_packages is undefined

- debug:
    msg: "Unhandled package type {{_packages|type_debug}}"
  when: >
    _packages|type_debug != "list" and
    _packages|type_debug != "dict"

- ansible.builtin.include_tasks: _install_package_list.yml
  when: >
    _packages|type_debug == "list"
