- ansible.builtin.set_fact: role_name="undefined"
  when: role_name is undefined

- ansible.builtin.set_fact:
    _packages: "{{role_packages}}"
  when: role_packages is defined

- ansible.builtin.set_fact:
    _update_cache: "{{update_repo_cache}}"
  when: update_repo_cache is defined

- ansible.builtin.set_fact:
    _packages: "{{packages}}"
  when: packages is defined and role_packages is undefined

- ansible.builtin.include_tasks: _install_package_list.yml
  when: >
    role_bootstrap_packages is defined and
    role_bootstrap_packages|type_debug == "list"
  vars:
    _packages: "{{role_bootstrap_packages}}"
    _bootstrap: true

- debug:
    msg: "Unhandled package type {{_packages|type_debug}} for {{_packages}}"
  when: >
    _packages|type_debug != "list" and
    _packages|type_debug != "dict"

- ansible.builtin.include_tasks: _install_package_list.yml
  when: >
    _packages|type_debug == "list"
