#- ansible.builtin.include_tasks: _manage_windows_hostname.yml
#  when: >
#    ansible_os_family == "Windows"

- name: try setting up firewalld
  ansible.builtin.include_tasks: _manage_linux_firewall.yml
  when: >
    ansible_os_family != "Windows" and
    ansible_os_family != "Darwin"