- name: set default password store (legacy)
  ansible.builtin.set_fact:
    passdb: passwordstore
  when: >
    passdb is undefined and
    ansible_version.full is version('2.9', '>=') and
    ansible_version.full is version('2.10', '<')
  tags:
    - base_config
    - access_setup

- name: set default password store (legacy)
  ansible.builtin.set_fact:
    passdb: community.general.passwordstore
  when: >
    passdb is undefined and
    ansible_version.full is version('2.10', '>=')
  tags:
    - base_config
    - access_setup

- name: set default password length
  ansible.builtin.set_fact:
    passdb_password_length: 20
  when: passdb_password_length is undefined
  tags:
    - base_config
    - access_setup

- name: set default for password creation
  ansible.builtin.set_fact:
    passdb_password_create: True
  when: passdb_password_create is undefined
  tags:
    - base_config
    - access_setup

- name: set passdb extra arguments
  ansible.builtin.set_fact:
    passdb_extra_arg: " create={{passdb_password_create}} length={{passdb_password_length}}"
  when: passdb_extra_arg is undefined
  tags:
    - base_config
    - access_setup

- set_fact:
    default_passdb_available: False
  tags:
    - base_config
    - access_setup

- name: check default password store access
  ansible.builtin.set_fact:
    _passdb_check_value: "{{lookup(passdb, passdb_check_entry)}}"
  register: _passdb_result
  ignore_errors: True
  when: >
    passdb_check_entry is defined
  tags:
    - base_config
    - access_setup

# This is for backwards compatibility. This will fail during execution if
# password store is not available
- name: setting default password store availability to true without check
  ansible.builtin.set_fact:
    default_passdb_available: True
  when: _passdb_result is skipped
  tags:
    - base_config
    - access_setup

- name: setting default password store availability to true
  ansible.builtin.set_fact:
    default_passdb_available: True
  when: _passdb_result is succeeded
  tags:
    - base_config
    - access_setup

- ansible.builtin.debug: msg="Passdb is not available, some roles may fail"
  when: _passdb_result is failed
  tags:
    - base_config
    - access_setup