name: shared container builder
description: log in to GHCR and run kiwi build action
inputs:
  image-directory:
    description: 'Directory for the image build'
    required: false
    default: 'container-image'
  extra-repositories:
    description: 'Extra repo URLs for kiwi-build'
    required: false
    default: ''
  git-tag:
    description: 'Git tag to push in addition to the kiwi version tag and latest'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: 'Login to GitHub Container Registry'
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build leap base image
      uses: aardsoft/ci-actions/kiwi-build@master
      with:
        image-directory: ${{ inputs.image-directory }}
        extra-repositories: ${{ inputs.extra-repositories }}
        git-tag: ${{ inputs.git-tag }}
