# run with a user already having access to the target system:
#
# ansible-playbook access.yml -u <user> -b --become-method=su
#
# ansible-playbook access.yml --tags "access_setup" -u <user> -b
#
# --ask-pass and --ask-become-pass might be required as well
#
# If the SSH session hangs SSH might be trying to use a key for
# authentication, even if a password was provided. To disable this
# add --ssh-common-args "-o PubkeyAuthentication=no"
#
# su support seems to be fully broken in ansible currently:
# - "su: must be run from a terminal\n"
# - http://grokbase.com/t/gg/ansible-project/159281vzpx/is-su-exe-become-exe-broken-in-v2

- hosts: all
  name: Check bootstrap arguments
  gather_facts: false
  tasks:
    - fail: msg='Limit scope using --tags "access_setup"'

- hosts: all
  name: Bootstrap python
  gather_facts: false
  tasks:
    - name: register script
      include_role:
        name: data-utilities
        tasks_from: pack_python_bootstrap
    - name: dump script contents
      debug:
        msg: "{{bootstrap_script}}"
    - name: bootstrap python, if missing
      raw: "echo {{bootstrap_script}} | base64 -d > /tmp/python-installer; bash /tmp/python-installer"
      args:
        executable: /bin/bash
      register: output
      changed_when: output.stdout != ""
      ignore_errors: true
    - name: Gathering Facts
      setup:
  tags:
    - access_setup

#- hosts: all
#  become: True
#  tasks:
#    - name: dump hostvars
#      debug: msg="{{hostvars[inventory_hostname]}}"
#  tags:
#    - access_setup

- hosts: all
  name: Bootstrap node
  roles:
    - basic-host
