name: shared container builder

on:
  workflow_call:
    inputs:
      image-directory:
        required: false
        type: string
        default: 'container-image'
      extra-repositories:
        required: false
        type: string
        default: ''
      extra-architectures:
        description: 'Space-separated architectures to build via QEMU emulation (e.g. "aarch64")'
        required: false
        type: string
        default: ''

jobs:
  build-images:
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: Checkout Calling Repository
        uses: actions/checkout@v4

      - name: Detect git tag
        id: refs
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "git_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "git_tag=" >> $GITHUB_OUTPUT
          fi

      - name: Build
        uses: aardsoft/ci-actions/kiwi-build-multiarch@master
        with:
          image-directory: ${{ inputs.image-directory }}
          extra-repositories: ${{ inputs.extra-repositories }}
          extra-architectures: ${{ inputs.extra-architectures }}
          git-tag: ${{ steps.refs.outputs.git_tag }}
