name: shared container builder

on:
  workflow_call:
    inputs:
      image-directory:
        required: false
        type: string
        default: 'container-image'
      extra-repositories: # Repos to pass through to kiwi
        required: false
        type: string
        default: ''

jobs:
  build-images:
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: Checkout Calling Repository
        uses: actions/checkout@v4

      - name: Detect git tag
        id: refs
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "git_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "git_tag=" >> $GITHUB_OUTPUT
          fi

      - name: Run Build Logic
        uses: aardsoft/ansible-data-utilities/.github/actions/container-build@master
        with:
          image-directory: ${{ inputs.image-directory }}
          extra-repositories: ${{ inputs.extra-repositories }}
          git-tag: ${{ steps.refs.outputs.git_tag }}
