name: CI run

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ansible: [ 2.9.17, 5.1 ]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: print run information
        run: |
          echo "Running on ${{ matrix.os }}"
          echo "Python: "
          python --version

      - name: install python packages
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-virtualenv
        if: matrix.os == 'ubuntu-20.04'

      - name: test ansible
        run: |
          echo "Testing ansible ${{ matrix.ansible }}"
          python3 -m virtualenv ansible-${{ matrix.ansible }} --system-site-packages
          source ansible-${{ matrix.ansible }}/bin/activate
          python3 -m pip install ansible==${{ matrix.ansible }}
          ansible-playbook tests/ansible-info.yml
          ansible-playbook tests/ansible-ci.yml -e destructive_tests=True
