name: run tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

# there still are a bunch of distributions out there with python 3.6 - ansible
# 9.x was the last one to support that, so for now we still support that.
# we probably don't need to support the EOL versions in between those and the
# current ones, but there's no harm in adding them to the test run here.
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ansible:
          - 9.13.0
          - 10.7.0
          - 11.13.0
          - 12.3.0
          - 13.4.0

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y

      - name: install python packages
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-virtualenv

      - name: print run information
        run: |
          echo "Running on ${{ matrix.os }}"
          echo "Python: "
          python3 --version

      - name: run tests
        run: |
          python3 -m virtualenv ansible-${{ matrix.ansible }} --system-site-packages
          source ansible-${{ matrix.ansible }}/bin/activate
          python3 -m pip install ansible==${{ matrix.ansible }} netaddr pytest
          # typically the role would also clone that - but we need it there already for the inventory
          # plugin functionality
          git clone https://github.com/aardsoft/ansible-data-utilities.git playbooks/roles/data-utilities
          if [ -d tests/unit ]; then
            pytest
          fi
          ansible-playbook playbooks/test.yml
          # not sure if those old runs still add any value
          if [ -f tests/ansible-info.yml ]; then
            ansible-playbook tests/ansible-info.yml
          fi
          if [ -f tests/ansible-ci.yml ]; then
            ansible-playbook tests/ansible-ci.yml -e destructive_tests=True
          fi
