name: run tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ansible:
          - 9.13.0
          - 10.7.0
          - 11.4.0

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y

      - name: install python packages
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-virtualenv

      - name: print run information
        run: |
          echo "Running on ${{ matrix.os }}"
          echo "Python: "
          python3 --version

      - name: run tests
        run: |
          python3 -m virtualenv ansible-${{ matrix.ansible }} --system-site-packages
          source ansible-${{ matrix.ansible }}/bin/activate
          python3 -m pip install ansible==${{ matrix.ansible }} netaddr
          ansible-playbook playbooks/test.yml
